name: Ubuntu Linux Build

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'ubuntu latest'

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
    - name: Create executable
      uses: sayyid5416/pyinstaller@v1.8.0
      with:
        python_ver: '3.12'
        pyinstaller_ver: '==6.12.0'
        spec: 'src/QtTinySA.spec'
        requirements: 'src/requirements.txt'
        exe_path: './dist'
        upload_exe_with_name: 'QtTinySA'
