name: Windows Build

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      tags:
       description: 'windows latest'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r src/requirements.txt

      - name: Build with PyInstaller
        run: |
          cd src
          pyinstaller QtTinySA.spec
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtTinySA_win.exe
          path: src/dist/QtTinySA
